In [2]:
import numpy as np
import pandas as pd

scores = np.random.randint(40, high=101, size=(50, 5))
scores_df = pd.DataFrame(scores,
    columns=['國文', '英文', '數學', '地理', '歷史'],
    index=range(1,51))
scores_df.index.name = "學號"
scores_df.columns.name="科目"
sum_series = scores_df.sum(axis=1)
mean_series = scores_df.mean(axis=1)
#display(sum_series)
rank_series = sum_series.rank(method='min',ascending=False)
scores_df["總分"] = sum_series
scores_df["平均"] = mean_series
scores_df["名次"] = rank_series
scores_df.sort_values(by='名次')

科目   國文  英文  數學  地理  歷史   總分    平均    名次
學號
11   95  84  91  95  66  431  86.2   1.0
14   62  99  77  98  91  427  85.4   2.0
40   63  95  63  96  98  415  83.0   3.0
24   88  63  97  63  93  404  80.8   4.0
1    88  58  69  91  89  395  79.0   5.0
20   73  93  41  95  90  392  78.4   6.0
29   92  85  52  96  65  390  78.0   7.0
28   41  90  92  77  87  387  77.4   8.0
23   97  61  85  69  75  387  77.4   8.0
37  100  69  89  49  79  386  77.2  10.0
43   97  84  98  51  55  385  77.0  11.0
30   51  81  83  68  97  380  76.0  12.0
50   95  61  56  71  97  380  76.0  12.0
8    61  94  88  61  76  380  76.0  12.0
39   99  65  72  52  91  379  75.8  15.0
44   63  87  98  68  63  379  75.8  15.0
22   75  98  93  59  50  375  75.0  17.0
3    96  55  74  56  93  374  74.8  18.0
38   44  97  49  98  83  371  74.2  19.0
7    54  97  65  56  97  369  73.8  20.0
31   95  46  85  74  58  358  71.6  21.0
27   74  45  84  92  62  357  71.4  22.0
5    78  83  65  67  63  356  71.2  23.0
45   80  84  78  48  65  355  71.0  24.0
17   78  85  53  42  96  354  70.8  25.0
15   66  85  88  67  46  352  70.4  26.0
36   79  92  45  41  87  344  68.8  27.0
35   86  61  95  48  53  343  68.6  28.0
42   88  51  76  46  82  343  68.6  28.0
6    66  40  92  80  63  341  68.2  30.0
46   84  82  60  50  55  331  66.2  31.0
41   89  78  40  73  49  329  65.8  32.0
49   70  53  84  69  53  329  65.8  32.0
18   70  71  93  45  50  329  65.8  32.0
16   42  45  86  98  57  328  65.6  35.0
13   91  46  49  85  55  326  65.2  36.0
12   85  68  46  64  61  324  64.8  37.0
21   80  82  75  40  45  322  64.4  38.0
19   65  54  76  56  63  314  62.8  39.0
33   51  40  50  90  82  313  62.6  40.0
2    69  51  76  53  64  313  62.6  40.0
9    41  97  55  62  56  311  62.2  42.0
25   61  71  68  60  43  303  60.6  43.0
10   45  90  66  45  52  298  59.6  44.0
32   51  48  85  55  59  298  59.6  44.0
48   71  40  54  68  61  294  58.8  46.0
4    46  40  65  92  50  293  58.6  47.0
26   43  94  44  44  60  285  57.0  48.0
34   61  51  59  61  52  284  56.8  49.0
47   65  53  60  60  44  282  56.4  50.0

In [3]:
def fun1(series:pd.Series) -> pd.Series: 
    min = series.min()
    median = series.median()
    max = series.max()  
    s1 = pd.Series([min,median,max],index=["最低分","中間值","最高分"])
    return s1

subject_df = scores_df[['國文', '英文', '數學', '地理', '歷史']]

frame1 = subject_df.apply(fun1)
frame1

科目      國文    英文    數學    地理    歷史
最低分   41.0  40.0  40.0  40.0  43.0
中間值   72.0  71.0  74.5  63.5  63.0
最高分  100.0  99.0  98.0  98.0  98.0

In [5]:
def fun2(series:pd.Series) -> pd.Series:
    lessThen60 = series[series<60].count()
    return pd.Series([lessThen60],index=['不及格科目'])

display(subject_df.T)

學號,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
科目,,,,,,,,,,,,,,,,,,,,,
國文,88,69,96,46,78,66,54,61,41,45,...,89,88,97,63,80,84,65,71,70,95
英文,58,51,55,40,83,40,97,94,97,90,...,78,51,84,87,84,82,53,40,53,61
數學,69,76,74,65,65,92,65,88,55,66,...,40,76,98,98,78,60,60,54,84,56
地理,91,53,56,92,67,80,56,61,62,45,...,73,46,51,68,48,50,60,68,69,71
歷史,89,64,93,50,63,63,97,76,56,52,...,49,82,55,63,65,55,44,61,53,97

In [4]:
def fun2(series:pd.Series) -> pd.Series:
    lessThen60 = series[series<60].count()    
    chinese = "及格" if(series['國文'] >= 60) else "不及格"
    english = "及格" if(series['英文'] >= 60) else "不及格"

    return pd.Series([lessThen60,chinese,english],index=['不及格科目',"國文","英文"])

display(subject_df.T)
subject_df.T.apply(fun2).T

學號,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
科目,,,,,,,,,,,,,,,,,,,,,
國文,88,69,96,46,78,66,54,61,41,45,...,89,88,97,63,80,84,65,71,70,95
英文,58,51,55,40,83,40,97,94,97,90,...,78,51,84,87,84,82,53,40,53,61
數學,69,76,74,65,65,92,65,88,55,66,...,40,76,98,98,78,60,60,54,84,56
地理,91,53,56,92,67,80,56,61,62,45,...,73,46,51,68,48,50,60,68,69,71
歷史,89,64,93,50,63,63,97,76,56,52,...,49,82,55,63,65,55,44,61,53,97

   不及格科目   國文   英文
學號
1      1   及格  不及格
2      2   及格  不及格
3      2   及格  不及格
4      3  不及格  不及格
5      0   及格   及格
6      1   及格  不及格
7      2  不及格   及格
8      0   及格   及格
9      3  不及格   及格
10     3  不及格   及格
11     0   及格   及格
12     1   及格   及格
13     3   及格  不及格
14     0   及格   及格
15     1   及格   及格
16     3  不及格  不及格
17     2   及格   及格
18     2   及格   及格
19     2   及格  不及格
20     1   及格   及格
21     2   及格   及格
22     2   及格   及格
23     0   及格   及格
24     0   及格   及格
25     1   及格   及格
26     3  不及格   及格
27     1   及格  不及格
28     1  不及格   及格
29     1   及格   及格
30     1  不及格   及格
31     2   及格  不及格
32     4  不及格  不及格
33     3  不及格  不及格
34     3   及格  不及格
35     2   及格   及格
36     2   及格   及格
37     1   及格   及格
38     2  不及格   及格
39     1   及格   及格
40     0   及格   及格
41     2   及格   及格
42     2   及格  不及格
43     2   及格   及格
44     0   及格   及格
45     1   及格   及格
46     2   及格   及格
47     2   及格  不及格
48     2   及格  不及格
49     2   及格  不及格
50     1   及格   及格